### PR TITLE
Share files from central google drive

### PR DESCRIPTION
**Pull request by hleeldc**
- Exposed a new method for sharing files from central google drive to
  private google drive.
- Also, reorganized the directory structure and namespace.
- New jar name is "cloud-server".
- Started a new version: cloud server 1.0.0.

### CODE REVIEW

**Comment by hleeldc** [comment]
This resolved issue #370.

**Comment by hleeldc** [comment]
Also, this depends on PR #397.

**Comment by hleeldc** [comment]
I tested this while testing PR #396.

**Comment by hleeldc** [comment]
Indexing was broken while new feature was being added. This has been fixed. The server has been deployed with the fix.

**Comment by stevenbird** [comment]
@lisaslyis would you please review and merge?

**Comment by hleeldc** [comment]
This PR has been moved to a new PR because the target branch has changed.

**Pull request closed without merging**
